{
 "title": "Triton",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(nv_inference_request_success{model=\"recipe_model\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User Feedback Rejection Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(model_feedback_negative_total[1h]))\n/\n(\n  sum(rate(model_feedback_positive_total[1h])) +\n  sum(rate(model_feedback_negative_total[1h]))\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Triton average inference latency (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(nv_inference_request_duration_us{model=\"recipe_model\"}[1h])\n/\nincrease(nv_inference_request_success{model=\"recipe_model\"}[1h])\n/ 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Triton Inference Request Failure Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(increase(nv_inference_request_failure{model=\"recipe_model\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Triton Inference Request Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "increase(nv_inference_request_success{model=\"recipe_model\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}