replicaCount: 1
service:
  port: 80
  externalIP: ""
resources:
  limits:
    cpu: "1000m"
    memory: "1Gi"
  requests:
    cpu: "500m"
    memory: "512Mi"
triton:
  serviceURL: "http://recipe-triton-svc.recipe-scraper-platform.svc.cluster.local:8000"
  modelName: "recipe_model"
