service:
  nodePort: 30900

env:
  modelVersion: staging
  extra:
    - name: RECIPE_SCRAPER_ENV
      value: staging

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: NotIn
              values:
                - node1
