{{- if or (not .Values.postgres.auth.existingSecret) (not .Values.mlflow.s3.existingSecret) }}
{{- if not .Values.postgres.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  username: {{ .Values.postgres.auth.username | quote }}
  password: {{ .Values.postgres.auth.password | quote }}
  dbname: {{ .Values.postgres.auth.database | quote }}
{{- end }}
{{- if and (not .Values.postgres.auth.existingSecret) (not .Values.mlflow.s3.existingSecret) }}
---
{{- end }}
{{- if not .Values.mlflow.s3.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: mlflow-s3-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.mlflow.s3.accessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.mlflow.s3.secretAccessKey | quote }}
  BUCKET_NAME: {{ .Values.mlflow.s3.bucketName | quote }}
{{- end }}
{{- end }}
