apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: recipe-triton-analysis
  namespace: {{ .Release.Namespace }}
spec:
  metrics:
    - name: user-feedback-rejection-rate
      interval: 6h
      count: 1
      failureLimit: 1
      successCondition: result < 0.25
      provider:
        prometheus:
          address: http://prometheus-svc.recipe-scraper-platform.svc.cluster.local:9090
          query: |
              scalar(
                sum(rate(model_feedback_negative_total[12h]))
                /
                (
                  sum(rate(model_feedback_positive_total[12h])) +
                  sum(rate(model_feedback_negative_total[12h]))
                )
              )
    - name: triton-error-rate
      interval: 2m
      count: 3
      failureLimit: 3
      successCondition: result < 0.05
      provider:
        prometheus:
          address: http://prometheus-svc.recipe-scraper-platform.svc.cluster.local:9090
          query: |
            scalar(
              sum(rate(nv_inference_request_failure[1h]))
              /
              (
                sum(rate(nv_inference_request_success[1h])) +
                sum(rate(nv_inference_request_failure[1h]))
              )
            )
    - name: triton-latency
      interval: 2m
      count: 3
      failureLimit: 3
      successCondition: result < 10000000
      provider:
        prometheus:
          address: http://prometheus-svc.recipe-scraper-platform.svc.cluster.local:9090
          query: |
            scalar(
              rate(nv_inference_request_duration_us[1h])
              /
              rate(nv_inference_request_success[1h])
            )
