apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: recipe-scraper-platform
resources:
  - rbac.yaml
  - workflow-template-training.yaml
  - cronworkflow-retraining.yaml
  - mlflow-model-promoter.yaml
