apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: recipe-scraper-staging
  namespace: argocd
spec:
  project: recipe-scraper
  source:
    repoURL: https://github.com/SofiaPapathanasiou/recipe-scraper-mlops.git
    targetRevision: HEAD
    path: devops/k8s/mealie
    helm:
      valueFiles:
        - values.yaml
        - values.staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: recipe-scraper-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
