apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie-cleaner
  namespace: recipe-scraper-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie-cleaner
  template:
    metadata:
      labels:
        app: mealie-cleaner
    spec:
      containers:
      - name: mealie-cleaner
        image: 192.168.1.11:5000/recipe-scraper-data:latest
        imagePullPolicy: Always
        command: ["python3", "/app/scripts/mealie_cleaner.py"]
        env:
        - name: DATA_ROOT
          value: /data
        - name: OS_AUTH_URL
          valueFrom:
            secretKeyRef:
              name: swift-credentials
              key: OS_AUTH_URL
        - name: OS_APPLICATION_CREDENTIAL_ID
          valueFrom:
            secretKeyRef:
              name: swift-credentials
              key: OS_APPLICATION_CREDENTIAL_ID
        - name: OS_APPLICATION_CREDENTIAL_SECRET
          valueFrom:
            secretKeyRef:
              name: swift-credentials
              key: OS_APPLICATION_CREDENTIAL_SECRET
        - name: OS_AUTH_TYPE
          valueFrom:
            secretKeyRef:
              name: swift-credentials
              key: OS_AUTH_TYPE
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: data-pvc-gpu
