
services:
  init-data:
    image: python:3.11
    volumes:
      - recipe-nlg:/data
      - ./:/src
    command:
      - bash
      - -lc
      - |
        set -e
        apt-get update
        apt-get install -y unzip
        unzip -j /src/eval.jsonl.zip -d /data
        ls -l /data
    restart: "no"

volumes:
  recipe-nlg:
    external: true