global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'triton'
    static_configs:
      # - targets: ['triton_server:8002']  run this wihtin same docker
      - targets: ['129.114.109.150:8002'] #run this when using my mini k8s cluster