---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-pvc
  namespace: recipe-scraper-mealie
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie
  namespace: recipe-scraper-mealie
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mealie
  template:
    metadata:
      labels:
        app: mealie
    spec:
      containers:
        - name: mealie
          image: ghcr.io/mealie-recipes/mealie:v3.14.0
          ports:
            - containerPort: 9000
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/New_York"
            - name: BASE_URL
              value: "http://{{ .Values.service.externalIP }}"
          volumeMounts:
            - name: mealie-data
              mountPath: /app/data
      volumes:
        - name: mealie-data
          persistentVolumeClaim:
            claimName: mealie-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mealie
  namespace: recipe-scraper-mealie
spec:
  selector:
    app: mealie
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9000
  externalIPs:
    - {{ .Values.service.externalIP }}
