apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-pvc
  namespace: recipe-scraper-mealie
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie
  namespace: recipe-scraper-mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie
  template:
    metadata:
      labels:
        app: mealie
    spec:
      containers:
      - name: mealie
        image: ghcr.io/mealie-recipes/mealie:v3.14.0
        ports:
        - containerPort: 9000
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/New_York"
        volumeMounts:
        - name: mealie-data
          mountPath: /app/data
      volumes:
      - name: mealie-data
        persistentVolumeClaim:
          claimName: mealie-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mealie
  namespace: recipe-scraper-mealie
spec:
  type: NodePort
  selector:
    app: mealie
  ports:
  - port: 80
    targetPort: 9000
    nodePort: 30900
